name: Ada.is
description: The blog of Ada Rose Cannon
author:
  name: Ada Rose Cannon
  email: ada@ada.is
  twitter: lady_ada_king

include: ['.htaccess']

# _config.build.yml sets future and show_drafts to false on `grunt build`
future: false
show_drafts: false

permalink: pretty

giturl: https://github.com/AdaRoseCannon
pageurl: /
pullreq: https://github.com/AdaRoseCannon/adarosecannon.github.io/tree/master/

